{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ include "hello-world-keda.fullname" . }}-gateway
  labels:
    {{- include "hello-world-keda.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.istio.gatewaySelector | nindent 4 }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.host | quote }}
{{- end }}
